version: "3.7"
services: 
    app:
        container_name: api
        build:
            context: .
        command: "./wait-for-it.sh db:3306 --strict --timeout=300 -- node server.js"
        ports: 
            - "4000:4000"
        depends_on: 
            - db
        env_file:
           - .env

    db:
       image: "mysql:5.7"
       environment: 
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASS}
        
       ports: 
            - "9003:3306"
